---
- name: Restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Apply and save iptables rules
  ansible.builtin.shell: |
    /usr/local/sbin/iptables-rules.sh
    ipset save > /etc/iptables/ipsets
    netfilter-persistent save
